## Travis CI configuration for the cookiecutter-cpp-lib project template.
##
##   <https://travis-ci.org/mdklatt/cookiecutter-cpp-lib>
##
language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - master
    - dev

dist: xenial

before_script:
  # Install Cookiecutter. Because this is a C++ project a Python virtualenv
  # environment needs to be created manually.
  - pyenv local 3.6.7
  - python -m pip install --requirement=requirements.txt
  
script:
  - python tests/test_template.py
